<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>14.0</LangVersion>
    <Company>Starion Group S.A.</Company>
    <Authors>Sam Gerene</Authors>
    <Description>Nunit test suite for the SysML2.NET.CodeGenerator</Description>
    <Copyright>Copyright © Starion Group S.A.</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/STARIONGROUP/SysML2.NET.git</RepositoryUrl>
    <RepositoryType>Git</RepositoryType>
    <ImplicitUsings>false</ImplicitUsings>
    <Nullable>disable</Nullable>
    <IsPackable>false</IsPackable>
    <PreserveCompilationContext>true</PreserveCompilationContext>
    <SatelliteResourceLanguages>en-US</SatelliteResourceLanguages>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Extensions\**" />
    <EmbeddedResource Remove="Extensions\**" />
    <None Remove="Extensions\**" />
    <Compile Include="Extensions\*TestFixture.cs" />
    <Compile Remove="Expected\OpenAPI\**" />
    <Compile Remove="Expected\UML\**" />
    <None Include="Expected\OpenAPI\**\*.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="Expected\UML\**\*.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="10.0.11" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
    <PackageReference Include="NUnit" Version="4.6.1" />
    <PackageReference Include="NUnit.Console" Version="3.22.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="6.3.0" />
    <PackageReference Include="coverlet.collector" Version="10.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.msbuild" Version="10.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Serilog" Version="4.4.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="uml4net.Reporting" Version="8.6.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SysML2.NET.CodeGenerator\SysML2.NET.CodeGenerator.csproj" />
  </ItemGroup>
</Project>