// -------------------------------------------------------------------------------------------------
// <copyright file="ExternalRelationshipRequestSerializer.cs" company="Starion Group S.A.">
//
//    Copyright (C) 2022-2026 Starion Group S.A.
//
//    Licensed under the Apache License, Version 2.0 (the "License");
//    you may not use this file except in compliance with the License.
//    You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//
// </copyright>
// ------------------------------------------------------------------------------------------------

// ------------------------------------------------------------------------------------------------
// <auto-generated />
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------

namespace SysML2.NET.Serializer.Json.PSM
{
    using System;
    using System.Text.Json;

    using SysML2.NET.PSM.DTO;
    using SysML2.NET.PSM.Enumerations;
    using SysML2.NET.Serializer.Json;

    /// <summary>
    /// The purpose of the <see cref="ExternalRelationshipRequestSerializer"/> is to provide serialization capabilities
    /// for the <see cref="ExternalRelationshipRequest"/> class
    /// </summary>
    internal static class ExternalRelationshipRequestSerializer
    {
        /// <summary>
        /// Serializes an instance of <see cref="ExternalRelationshipRequest"/> using an <see cref="Utf8JsonWriter"/>
        /// </summary>
        /// <param name="obj">
        /// The <see cref="ExternalRelationshipRequest"/> to serialize
        /// </param>
        /// <param name="writer">
        /// The target <see cref="Utf8JsonWriter"/>
        /// </param>
        /// <param name="serializationModeKind">
        /// enumeration specifying what kind of serialization shall be used
        /// </param>
        /// <param name="includeDerivedProperties">
        /// Asserts that derived properties should also be part of the serialization
        /// </param>
        /// <exception cref="ArgumentException">
        /// Thrown when the object is not a <see cref="ExternalRelationshipRequest"/>
        /// </exception>
        /// <exception cref="NotSupportedException">
        /// Thrown when the serialization mode is not supported
        /// </exception>
        internal static void Serialize(object obj, Utf8JsonWriter writer, SerializationModeKind serializationModeKind, bool includeDerivedProperties)
        {
            if (obj is not ExternalRelationshipRequest externalRelationshipRequest)
            {
                throw new ArgumentException("The object shall be a ExternalRelationshipRequest", nameof(obj));
            }

            if (serializationModeKind != SerializationModeKind.JSON)
            {
                throw new NotSupportedException($"The {serializationModeKind} serialization mode is not supported");
            }

            writer.WriteStartObject();

            writer.WriteString("@type"u8, "ExternalRelationship");

            if (externalRelationshipRequest.Id.HasValue)
            {
                writer.WriteString("@id"u8, externalRelationshipRequest.Id.Value);
            }
            else
            {
                writer.WriteNull("@id"u8);
            }

            if (externalRelationshipRequest.ElementEnd.HasValue)
            {
                writer.WriteStartObject("elementEnd"u8);
                writer.WriteString("@id"u8, externalRelationshipRequest.ElementEnd.Value);
                writer.WriteEndObject();
            }
            else
            {
                writer.WriteNull("elementEnd"u8);
            }

            if (externalRelationshipRequest.ExternalDataEnd.HasValue)
            {
                writer.WriteStartObject("externalDataEnd"u8);
                writer.WriteString("@id"u8, externalRelationshipRequest.ExternalDataEnd.Value);
                writer.WriteEndObject();
            }
            else
            {
                writer.WriteNull("externalDataEnd"u8);
            }

            writer.WriteString("language"u8, externalRelationshipRequest.Language);

            writer.WriteString("specification"u8, externalRelationshipRequest.Specification);

            writer.WriteEndObject();
        }
    }
}

// ------------------------------------------------------------------------------------------------
// --------THIS IS AN AUTOMATICALLY GENERATED FILE. ANY MANUAL CHANGES WILL BE OVERWRITTEN!--------
// ------------------------------------------------------------------------------------------------
