// -------------------------------------------------------------------------------------------------
// <copyright file="LibraryRedirectingExternalReferenceService.cs" company="Starion Group S.A.">
//
//   Copyright (C) 2022-2026 Starion Group S.A.
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//        http://www.apache.org/licenses/LICENSE-2.0
//
//    Unless required by applicable law or agreed to in writing, software
//    distributed under the License is distributed on an "AS IS" BASIS,
//    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//    See the License for the specific language governing permissions and
//    limitations under the License.
//
// </copyright>
// ------------------------------------------------------------------------------------------------

namespace SysML2.NET.Serializer.TextualNotation.Tests.Wrapper
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    using Microsoft.Extensions.Logging;

    using SysML2.NET.Serializer.Xmi;

    /// <summary>
    /// Test-only <see cref="IExternalReferenceService" /> that redirects <c>href</c> references
    /// originally generated against a <c>sysml.library/</c> tree (pilot-implementation layout)
    /// to a locally available copy of those library files — typically the
    /// <c>SysML2.NET.Serializer.Xmi.Tests/Resources</c> tree mirrored into the test output
    /// folder by the test project's csproj.
    /// <para>
    /// The <c>sysmlx</c> / <c>kermlx</c> files under test are generated by the pilot implementation
    /// and emit hrefs of the form <c>../../../../sysml.library/Domain%20Libraries/.../SI.sysmlx</c>.
    /// Those paths do not exist on the test machine. Rather than editing the generated files,
    /// this service intercepts each href, detects the <c>sysml.library/</c> marker segment, and
    /// rebuilds the absolute path against <paramref name="libraryRoot" />, preserving everything
    /// after the marker. Hrefs without the marker fall back to the standard relative-to-current
    /// resolution used by <see cref="ExternalReferenceService" />.
    /// </para>
    /// </summary>
    public sealed class LibraryRedirectingExternalReferenceService : IExternalReferenceService
    {
        /// <summary>
        /// Marker substring identifying the pilot-implementation library root inside an href.
        /// Everything after this segment is treated as a path relative to <see cref="libraryRoot" />.
        /// </summary>
        private const string LibraryMarker = "sysml.library/";

        /// <summary>
        /// External references queued for processing.
        /// </summary>
        private readonly HashSet<Uri> pendingReferences = [];

        /// <summary>
        /// External references already returned via <see cref="GetExternalReferencesToProcess" />.
        /// </summary>
        private readonly HashSet<Uri> processedReferences = [];

        /// <summary>
        /// The local folder that mirrors the pilot-implementation <c>sysml.library</c> tree —
        /// typically the test output <c>Resources</c> folder.
        /// </summary>
        private readonly string libraryRoot;

        /// <summary>
        /// The injected logger used to surface redirect and dedupe events.
        /// </summary>
        private readonly ILogger<LibraryRedirectingExternalReferenceService> logger;

        /// <summary>
        /// Initializes a new instance of the <see cref="LibraryRedirectingExternalReferenceService" /> class.
        /// </summary>
        /// <param name="libraryRoot">
        /// Absolute path to the local folder that mirrors the pilot-implementation
        /// <c>sysml.library</c> tree (e.g. the test output <c>Resources</c> folder).
        /// </param>
        /// <param name="logger">The injected <see cref="ILogger{TCategoryName}" /> producing logs.</param>
        /// <exception cref="ArgumentNullException">When <paramref name="libraryRoot" /> is <see langword="null" />.</exception>
        public LibraryRedirectingExternalReferenceService(string libraryRoot, ILogger<LibraryRedirectingExternalReferenceService> logger)
        {
            this.libraryRoot = libraryRoot ?? throw new ArgumentNullException(nameof(libraryRoot));
            this.logger = logger;
        }

        /// <summary>
        /// Resolves <paramref name="externalReference" /> against <paramref name="currentLocation" />,
        /// redirecting any path containing the <c>sysml.library/</c> marker to
        /// <see cref="libraryRoot" />, and queues the resulting absolute <see cref="Uri" /> for
        /// processing. Already-processed references are skipped.
        /// </summary>
        /// <param name="currentLocation">The <see cref="Uri" /> of the file currently being read.</param>
        /// <param name="externalReference">The raw href value (without fragment) emitted by the reader.</param>
        public void AddExternalReferenceToProcess(Uri currentLocation, string externalReference)
        {
            var unescaped = Uri.UnescapeDataString(externalReference);
            var resolvedUri = this.Redirect(currentLocation, unescaped);

            if (!this.processedReferences.Contains(resolvedUri))
            {
                this.pendingReferences.Add(resolvedUri);
            }
            else
            {
                if (this.logger?.IsEnabled(LogLevel.Information) == true)
                {
                    this.logger.LogInformation("File {FileName} already processed", new FileInfo(resolvedUri.LocalPath).Name);
                }
            }
        }

        /// <summary>
        /// Returns the queued references and marks them as processed so a subsequent
        /// <see cref="AddExternalReferenceToProcess" /> call for the same target is deduped.
        /// </summary>
        /// <returns>The references to deserialize next.</returns>
        public IReadOnlyCollection<Uri> GetExternalReferencesToProcess()
        {
            var toBeProcessed = new List<Uri>(this.pendingReferences);

            foreach (var uri in toBeProcessed)
            {
                this.processedReferences.Add(uri);
            }

            this.pendingReferences.Clear();
            return toBeProcessed;
        }

        /// <summary>
        /// Computes the absolute <see cref="Uri" /> for an href: when the href contains the
        /// <c>sysml.library/</c> marker, the redirect replaces the marker prefix with
        /// <see cref="libraryRoot" />; otherwise the href is resolved against
        /// <paramref name="currentLocation" /> using the standard <see cref="Uri" /> constructor —
        /// matching the production <see cref="ExternalReferenceService" /> behavior so secondary
        /// library-to-library hrefs (already relative to the local <c>libraryRoot</c> layout) resolve naturally.
        /// </summary>
        /// <param name="currentLocation">The <see cref="Uri" /> of the file currently being read.</param>
        /// <param name="unescapedHref">The href value already unescaped via <see cref="Uri.UnescapeDataString(string)" />.</param>
        /// <returns>The absolute <see cref="Uri" /> to the file to deserialize.</returns>
        private Uri Redirect(Uri currentLocation, string unescapedHref)
        {
            var markerIndex = unescapedHref.IndexOf(LibraryMarker, StringComparison.Ordinal);

            if (markerIndex < 0)
            {
                return new Uri(currentLocation, unescapedHref);
            }

            var subPath = unescapedHref.Substring(markerIndex + LibraryMarker.Length);
            var redirectedPath = Path.GetFullPath(Path.Combine(this.libraryRoot, subPath));

            if (this.logger?.IsEnabled(LogLevel.Information) == true)
            {
                this.logger.LogInformation("Redirected href '{Href}' to '{Redirected}'", unescapedHref, redirectedPath);
            }

            return new Uri(redirectedPath);
        }
    }
}
