//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/CODE/SysML2.NET/Resources/kebnf.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SysML2.NET.CodeGenerator.Grammar {
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class kebnfLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, ASSIGN=8, ADD_ASSIGN=9, 
		BOOL_ASSIGN=10, PIPE=11, COLON=12, SEMICOLON=13, COMMA=14, LPAREN=15, 
		RPAREN=16, LBRACK=17, RBRACK=18, LBRACE=19, RBRACE=20, DOT=21, TILDE=22, 
		ID=23, INT=24, STRING=25, COMMENT=26, WS=27, CONTINUATION=28, NL=29;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"T__0", "T__1", "T__2", "T__3", "T__4", "T__5", "T__6", "ASSIGN", "ADD_ASSIGN", 
		"BOOL_ASSIGN", "PIPE", "COLON", "SEMICOLON", "COMMA", "LPAREN", "RPAREN", 
		"LBRACK", "RBRACK", "LBRACE", "RBRACE", "DOT", "TILDE", "ID", "INT", "STRING", 
		"COMMENT", "WS", "CONTINUATION", "NL"
	};


	public kebnfLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public kebnfLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'*'", "'+'", "'?'", "'true'", "'false'", "'this'", "'[QualifiedName]'", 
		null, "'+='", "'?='", "'|'", "':'", "';'", "','", "'('", "')'", "'['", 
		"']'", "'{'", "'}'", "'.'", "'~'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, "ASSIGN", "ADD_ASSIGN", 
		"BOOL_ASSIGN", "PIPE", "COLON", "SEMICOLON", "COMMA", "LPAREN", "RPAREN", 
		"LBRACK", "RBRACK", "LBRACE", "RBRACE", "DOT", "TILDE", "ID", "INT", "STRING", 
		"COMMENT", "WS", "CONTINUATION", "NL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "kebnf.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static kebnfLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,29,190,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,
		6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,2,14,
		7,14,2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,2,21,
		7,21,2,22,7,22,2,23,7,23,2,24,7,24,2,25,7,25,2,26,7,26,2,27,7,27,2,28,
		7,28,1,0,1,0,1,1,1,1,1,2,1,2,1,3,1,3,1,3,1,3,1,3,1,4,1,4,1,4,1,4,1,4,1,
		4,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,1,6,
		1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,3,7,102,8,7,1,8,1,8,1,8,1,9,1,9,1,9,1,
		10,1,10,1,11,1,11,1,12,1,12,1,13,1,13,1,14,1,14,1,15,1,15,1,16,1,16,1,
		17,1,17,1,18,1,18,1,19,1,19,1,20,1,20,1,21,1,21,1,22,1,22,5,22,136,8,22,
		10,22,12,22,139,9,22,1,23,4,23,142,8,23,11,23,12,23,143,1,24,1,24,1,24,
		1,24,5,24,150,8,24,10,24,12,24,153,9,24,1,24,1,24,1,25,1,25,1,25,1,25,
		5,25,161,8,25,10,25,12,25,164,9,25,1,25,1,25,1,26,4,26,169,8,26,11,26,
		12,26,170,1,26,1,26,1,27,3,27,176,8,27,1,27,1,27,4,27,180,8,27,11,27,12,
		27,181,1,27,1,27,1,28,3,28,187,8,28,1,28,1,28,0,0,29,1,1,3,2,5,3,7,4,9,
		5,11,6,13,7,15,8,17,9,19,10,21,11,23,12,25,13,27,14,29,15,31,16,33,17,
		35,18,37,19,39,20,41,21,43,22,45,23,47,24,49,25,51,26,53,27,55,28,57,29,
		1,0,6,3,0,65,90,95,95,97,122,4,0,48,57,65,90,95,95,97,122,1,0,48,57,2,
		0,39,39,92,92,2,0,10,10,13,13,2,0,9,9,32,32,199,0,1,1,0,0,0,0,3,1,0,0,
		0,0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,0,11,1,0,0,0,0,13,1,0,0,0,0,15,1,
		0,0,0,0,17,1,0,0,0,0,19,1,0,0,0,0,21,1,0,0,0,0,23,1,0,0,0,0,25,1,0,0,0,
		0,27,1,0,0,0,0,29,1,0,0,0,0,31,1,0,0,0,0,33,1,0,0,0,0,35,1,0,0,0,0,37,
		1,0,0,0,0,39,1,0,0,0,0,41,1,0,0,0,0,43,1,0,0,0,0,45,1,0,0,0,0,47,1,0,0,
		0,0,49,1,0,0,0,0,51,1,0,0,0,0,53,1,0,0,0,0,55,1,0,0,0,0,57,1,0,0,0,1,59,
		1,0,0,0,3,61,1,0,0,0,5,63,1,0,0,0,7,65,1,0,0,0,9,70,1,0,0,0,11,76,1,0,
		0,0,13,81,1,0,0,0,15,101,1,0,0,0,17,103,1,0,0,0,19,106,1,0,0,0,21,109,
		1,0,0,0,23,111,1,0,0,0,25,113,1,0,0,0,27,115,1,0,0,0,29,117,1,0,0,0,31,
		119,1,0,0,0,33,121,1,0,0,0,35,123,1,0,0,0,37,125,1,0,0,0,39,127,1,0,0,
		0,41,129,1,0,0,0,43,131,1,0,0,0,45,133,1,0,0,0,47,141,1,0,0,0,49,145,1,
		0,0,0,51,156,1,0,0,0,53,168,1,0,0,0,55,175,1,0,0,0,57,186,1,0,0,0,59,60,
		5,42,0,0,60,2,1,0,0,0,61,62,5,43,0,0,62,4,1,0,0,0,63,64,5,63,0,0,64,6,
		1,0,0,0,65,66,5,116,0,0,66,67,5,114,0,0,67,68,5,117,0,0,68,69,5,101,0,
		0,69,8,1,0,0,0,70,71,5,102,0,0,71,72,5,97,0,0,72,73,5,108,0,0,73,74,5,
		115,0,0,74,75,5,101,0,0,75,10,1,0,0,0,76,77,5,116,0,0,77,78,5,104,0,0,
		78,79,5,105,0,0,79,80,5,115,0,0,80,12,1,0,0,0,81,82,5,91,0,0,82,83,5,81,
		0,0,83,84,5,117,0,0,84,85,5,97,0,0,85,86,5,108,0,0,86,87,5,105,0,0,87,
		88,5,102,0,0,88,89,5,105,0,0,89,90,5,101,0,0,90,91,5,100,0,0,91,92,5,78,
		0,0,92,93,5,97,0,0,93,94,5,109,0,0,94,95,5,101,0,0,95,96,5,93,0,0,96,14,
		1,0,0,0,97,98,5,58,0,0,98,99,5,58,0,0,99,102,5,61,0,0,100,102,5,61,0,0,
		101,97,1,0,0,0,101,100,1,0,0,0,102,16,1,0,0,0,103,104,5,43,0,0,104,105,
		5,61,0,0,105,18,1,0,0,0,106,107,5,63,0,0,107,108,5,61,0,0,108,20,1,0,0,
		0,109,110,5,124,0,0,110,22,1,0,0,0,111,112,5,58,0,0,112,24,1,0,0,0,113,
		114,5,59,0,0,114,26,1,0,0,0,115,116,5,44,0,0,116,28,1,0,0,0,117,118,5,
		40,0,0,118,30,1,0,0,0,119,120,5,41,0,0,120,32,1,0,0,0,121,122,5,91,0,0,
		122,34,1,0,0,0,123,124,5,93,0,0,124,36,1,0,0,0,125,126,5,123,0,0,126,38,
		1,0,0,0,127,128,5,125,0,0,128,40,1,0,0,0,129,130,5,46,0,0,130,42,1,0,0,
		0,131,132,5,126,0,0,132,44,1,0,0,0,133,137,7,0,0,0,134,136,7,1,0,0,135,
		134,1,0,0,0,136,139,1,0,0,0,137,135,1,0,0,0,137,138,1,0,0,0,138,46,1,0,
		0,0,139,137,1,0,0,0,140,142,7,2,0,0,141,140,1,0,0,0,142,143,1,0,0,0,143,
		141,1,0,0,0,143,144,1,0,0,0,144,48,1,0,0,0,145,151,5,39,0,0,146,150,8,
		3,0,0,147,148,5,92,0,0,148,150,9,0,0,0,149,146,1,0,0,0,149,147,1,0,0,0,
		150,153,1,0,0,0,151,149,1,0,0,0,151,152,1,0,0,0,152,154,1,0,0,0,153,151,
		1,0,0,0,154,155,5,39,0,0,155,50,1,0,0,0,156,157,5,47,0,0,157,158,5,47,
		0,0,158,162,1,0,0,0,159,161,8,4,0,0,160,159,1,0,0,0,161,164,1,0,0,0,162,
		160,1,0,0,0,162,163,1,0,0,0,163,165,1,0,0,0,164,162,1,0,0,0,165,166,6,
		25,0,0,166,52,1,0,0,0,167,169,7,5,0,0,168,167,1,0,0,0,169,170,1,0,0,0,
		170,168,1,0,0,0,170,171,1,0,0,0,171,172,1,0,0,0,172,173,6,26,0,0,173,54,
		1,0,0,0,174,176,5,13,0,0,175,174,1,0,0,0,175,176,1,0,0,0,176,177,1,0,0,
		0,177,179,5,10,0,0,178,180,7,5,0,0,179,178,1,0,0,0,180,181,1,0,0,0,181,
		179,1,0,0,0,181,182,1,0,0,0,182,183,1,0,0,0,183,184,6,27,0,0,184,56,1,
		0,0,0,185,187,5,13,0,0,186,185,1,0,0,0,186,187,1,0,0,0,187,188,1,0,0,0,
		188,189,5,10,0,0,189,58,1,0,0,0,11,0,101,137,143,149,151,162,170,175,181,
		186,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace SysML2.NET.CodeGenerator.Grammar
