//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/CODE/SysML2.NET/Resources/kebnf.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SysML2.NET.CodeGenerator.Grammar {
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="kebnfParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IkebnfListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecification([NotNull] kebnfParser.SpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecification([NotNull] kebnfParser.SpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.rule_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRule_definition([NotNull] kebnfParser.Rule_definitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.rule_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRule_definition([NotNull] kebnfParser.Rule_definitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter_list([NotNull] kebnfParser.Parameter_listContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter_list([NotNull] kebnfParser.Parameter_listContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.alternatives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlternatives([NotNull] kebnfParser.AlternativesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.alternatives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlternatives([NotNull] kebnfParser.AlternativesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlternative([NotNull] kebnfParser.AlternativeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlternative([NotNull] kebnfParser.AlternativeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement([NotNull] kebnfParser.ElementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement([NotNull] kebnfParser.ElementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] kebnfParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] kebnfParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.non_parsing_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNon_parsing_assignment([NotNull] kebnfParser.Non_parsing_assignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.non_parsing_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNon_parsing_assignment([NotNull] kebnfParser.Non_parsing_assignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.non_parsing_empty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNon_parsing_empty([NotNull] kebnfParser.Non_parsing_emptyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.non_parsing_empty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNon_parsing_empty([NotNull] kebnfParser.Non_parsing_emptyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.cross_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCross_reference([NotNull] kebnfParser.Cross_referenceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.cross_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCross_reference([NotNull] kebnfParser.Cross_referenceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGroup([NotNull] kebnfParser.GroupContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGroup([NotNull] kebnfParser.GroupContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.terminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTerminal([NotNull] kebnfParser.TerminalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.terminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTerminal([NotNull] kebnfParser.TerminalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.non_terminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNon_terminal([NotNull] kebnfParser.Non_terminalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.non_terminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNon_terminal([NotNull] kebnfParser.Non_terminalContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.element_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElement_core([NotNull] kebnfParser.Element_coreContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.element_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElement_core([NotNull] kebnfParser.Element_coreContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.dotted_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDotted_id([NotNull] kebnfParser.Dotted_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.dotted_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDotted_id([NotNull] kebnfParser.Dotted_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.suffix_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSuffix_op([NotNull] kebnfParser.Suffix_opContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.suffix_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSuffix_op([NotNull] kebnfParser.Suffix_opContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.value_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue_literal([NotNull] kebnfParser.Value_literalContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.value_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue_literal([NotNull] kebnfParser.Value_literalContext context);
}
} // namespace SysML2.NET.CodeGenerator.Grammar
