//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/CODE/SysML2.NET/Resources/kebnf.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SysML2.NET.CodeGenerator.Grammar {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IkebnfListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class kebnfBaseListener : IkebnfListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSpecification([NotNull] kebnfParser.SpecificationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.specification"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSpecification([NotNull] kebnfParser.SpecificationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.rule_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRule_definition([NotNull] kebnfParser.Rule_definitionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.rule_definition"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRule_definition([NotNull] kebnfParser.Rule_definitionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParameter_list([NotNull] kebnfParser.Parameter_listContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.parameter_list"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParameter_list([NotNull] kebnfParser.Parameter_listContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.alternatives"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlternatives([NotNull] kebnfParser.AlternativesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.alternatives"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlternatives([NotNull] kebnfParser.AlternativesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.alternative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlternative([NotNull] kebnfParser.AlternativeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.alternative"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlternative([NotNull] kebnfParser.AlternativeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement([NotNull] kebnfParser.ElementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.element"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement([NotNull] kebnfParser.ElementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] kebnfParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] kebnfParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.non_parsing_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNon_parsing_assignment([NotNull] kebnfParser.Non_parsing_assignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.non_parsing_assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNon_parsing_assignment([NotNull] kebnfParser.Non_parsing_assignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.non_parsing_empty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNon_parsing_empty([NotNull] kebnfParser.Non_parsing_emptyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.non_parsing_empty"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNon_parsing_empty([NotNull] kebnfParser.Non_parsing_emptyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.cross_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCross_reference([NotNull] kebnfParser.Cross_referenceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.cross_reference"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCross_reference([NotNull] kebnfParser.Cross_referenceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGroup([NotNull] kebnfParser.GroupContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.group"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGroup([NotNull] kebnfParser.GroupContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.terminal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerminal([NotNull] kebnfParser.TerminalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.terminal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerminal([NotNull] kebnfParser.TerminalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.non_terminal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNon_terminal([NotNull] kebnfParser.Non_terminalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.non_terminal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNon_terminal([NotNull] kebnfParser.Non_terminalContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.element_core"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElement_core([NotNull] kebnfParser.Element_coreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.element_core"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElement_core([NotNull] kebnfParser.Element_coreContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.dotted_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDotted_id([NotNull] kebnfParser.Dotted_idContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.dotted_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDotted_id([NotNull] kebnfParser.Dotted_idContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.suffix_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSuffix_op([NotNull] kebnfParser.Suffix_opContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.suffix_op"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSuffix_op([NotNull] kebnfParser.Suffix_opContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="kebnfParser.value_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue_literal([NotNull] kebnfParser.Value_literalContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="kebnfParser.value_literal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue_literal([NotNull] kebnfParser.Value_literalContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace SysML2.NET.CodeGenerator.Grammar
