//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/CODE/SysML2.NET/Resources/kebnf.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace SysML2.NET.CodeGenerator.Grammar {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="kebnfParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IkebnfVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSpecification([NotNull] kebnfParser.SpecificationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.rule_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRule_definition([NotNull] kebnfParser.Rule_definitionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.parameter_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_list([NotNull] kebnfParser.Parameter_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.alternatives"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlternatives([NotNull] kebnfParser.AlternativesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.alternative"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlternative([NotNull] kebnfParser.AlternativeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.element"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement([NotNull] kebnfParser.ElementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] kebnfParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.non_parsing_assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_parsing_assignment([NotNull] kebnfParser.Non_parsing_assignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.non_parsing_empty"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_parsing_empty([NotNull] kebnfParser.Non_parsing_emptyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.cross_reference"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCross_reference([NotNull] kebnfParser.Cross_referenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.group"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGroup([NotNull] kebnfParser.GroupContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.terminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerminal([NotNull] kebnfParser.TerminalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.non_terminal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNon_terminal([NotNull] kebnfParser.Non_terminalContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.element_core"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElement_core([NotNull] kebnfParser.Element_coreContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.dotted_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDotted_id([NotNull] kebnfParser.Dotted_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.suffix_op"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSuffix_op([NotNull] kebnfParser.Suffix_opContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="kebnfParser.value_literal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitValue_literal([NotNull] kebnfParser.Value_literalContext context);
}
} // namespace SysML2.NET.CodeGenerator.Grammar
